// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'excerpt': string;
  'excerpt__btn': string;
  'excerpt__content': string;
  'excerpt__time': string;
}
export const cssExports: CssExports;
export default cssExports;
