// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'figure': string;
  'is-center-bottom': string;
  'is-center-top': string;
  'is-contain': string;
  'is-left-bottom': string;
  'is-left-center': string;
  'is-left-top': string;
  'is-right-bottom': string;
  'is-right-center': string;
  'is-right-top': string;
}
export const cssExports: CssExports;
export default cssExports;
