// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'animate-angle-close': string;
  'animate-angle-open': string;
  'animate-fade-in': string;
  'animate-fade-out': string;
  'animate-hide': string;
  'bg-color-1': string;
  'bg-color-2': string;
  'bg-color-3': string;
  'bg-color-4': string;
  'bg-dark': string;
  'bg-light': string;
  'border-b': string;
  'border-color-1': string;
  'border-color-2': string;
  'border-color-3': string;
  'border-color-4': string;
  'border-dark': string;
  'border-l': string;
  'border-l-r': string;
  'border-light': string;
  'border-r': string;
  'border-t': string;
  'border-t-r-l': string;
  'color-1': string;
  'color-2': string;
  'color-3': string;
  'color-4': string;
  'color-dark': string;
  'color-light': string;
  'kf-angle-close': string;
  'kf-angle-open': string;
  'kf-fade-in': string;
  'kf-fade-out': string;
}
export const cssExports: CssExports;
export default cssExports;
