// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'is-active': string;
  'menu': string;
  'menu__trigger': string;
  'menu__trigger-bar': string;
  'menu__trigger-container': string;
}
export const cssExports: CssExports;
export default cssExports;
