// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'header__inside': string;
  'is-active': string;
  'is-hidden': string;
}
export const cssExports: CssExports;
export default cssExports;
