// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'is-active': string;
  'menu': string;
  'menu__bar': string;
}
export const cssExports: CssExports;
export default cssExports;
