// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'is-active': string;
  'is-positioned': string;
  'menu': string;
  'nav': string;
  'trigger': string;
  'trigger__bar': string;
  'trigger__container': string;
}
export const cssExports: CssExports;
export default cssExports;
