// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'is-active': string;
  'nav': string;
  'nav__li': string;
}
export const cssExports: CssExports;
export default cssExports;
