// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'footer__social': string;
  'footer__social-link': string;
}
export const cssExports: CssExports;
export default cssExports;
