#!/bin/bash
#add-component

clear
ls pattern-library
echo ""
echo ""
read -p "Avalible components: copy component name paste press [ENTER]: " COMPONENT
echo ""
echo ""

if [ -d pattern-library/"$COMPONENT" ]; then
    cp -r pattern-library/"$COMPONENT" src/components
    echo Added: src/components/"$COMPONENT"
    echo Instructions: src/components/"$COMPONENT"/README.md for instructions

    read -p "Add another component

    [0] Yes
    [1] No

    [0/1]: " ADD_COMPONENT_SWITCH
    if [ "$ADD_COMPONENT_SWITCH" = "0" ]; then
        eval "sh .scripts/add-component"
    else
        echo "Toolkit Stopping"
    fi
else
    echo "$COMPONENT" does not exist, Toolkit Stopping
fi
