#!/bin/bash
# add-component

PATTERN_LIBRARY=($(ls pattern-library | grep -v "README.md"))

clear
echo ""
for index in "${!PATTERN_LIBRARY[@]}"; do
    echo "[$index] ${PATTERN_LIBRARY[$index]}"
done
echo ""

read -p "Enter the number corresponding to the component to copy and press [ENTER]: " COMPONENT_INDEX

if ! [[ "$COMPONENT_INDEX" =~ ^[0-9]+$ ]]; then
    echo "Invalid input. Please enter a number."
    exit 1
fi

if (( COMPONENT_INDEX >= 0 && COMPONENT_INDEX < ${#PATTERN_LIBRARY[@]} )); then
    COMPONENT="${PATTERN_LIBRARY[$COMPONENT_INDEX]}"

    if [ -d "pattern-library/$COMPONENT" ]; then
        cp -r "pattern-library/$COMPONENT" src/components
        echo "Added: src/components/$COMPONENT"
        echo "Instructions: src/components/$COMPONENT/README.md for instructions"
        eval "code ./src/config/modules.config.ts"
        eval "code ./src/components/$COMPONENT/README.md"
        echo ""
        echo ""
        read -p "Add another component? [0] Yes, [1] No: " ADD_COMPONENT_SWITCH

        if [ "$ADD_COMPONENT_SWITCH" = "0" ]; then
            eval "bash .scripts/add-component"
        else
            echo "Toolkit Stopping"
        fi
    else
        echo "$COMPONENT" does not exist, Toolkit Stopping
    fi
else
    echo "Invalid number. Please enter a valid number."
fi
