#!/bin/bash
#backup

read -p "Backup
Select environment

[0] Production
[1] Staging

[0/1]: " BACKUP_SWITCH
if [ "$BACKUP_SWITCH" = "0" ]; then
    SSH=$PRODUCTION_SSH
    DIR=$PRODUCTION_DIR
    ENVIRONMENT=production
elif [ "$BACKUP_SWITCH" = "1" ]; then
    SSH=$STAGING_SSH
    DIR=$STAGING_DIR
    ENVIRONMENT=staging
else
  echo "Environment not set, Toolkit Stopping"
fi

if [ "$ENVIRONMENT" ]; then
    echo "Backing up $ENVIRONMENT"
    ssh "$SSH" "cd $DIR; wp db export backup.sql; zip -r backup.zip backup.sql $WP_UPLOADS"
    eval rsync "$SSH":"$DIR"/backup.zip "$LOCAL_DIR" --stats --progress -zvrt --update
    eval mv "$LOCAL_DIR"/backup.zip "$BACKUP_DIR"/backup-env-"$ENVIRONMENT"-date-$(date +"%Y-%m-%d").zip
    ssh "$SSH" "cd $DIR; rm -rf backup.zip backup.sql"
    echo "Backup of $ENVIRONMENT created $(date +"%Y-%m-%d") moved to $BACKUP_DIR"
else
  echo "Environment not set, Toolkit Stopping"
fi
