#!/bin/bash
#db-push

read -p "Database Push
Select Environment

[0] Production
[1] Staging

[0/1]: " DB_PUSH_SWITCH
if [ "$DB_PUSH_SWITCH" = "0" ]; then
    SSH=$PRODUCTION_SSH
    DIR=$PRODUCTION_DIR
    URL=$PRODUCTION_URL
    ENVIRONMENT=production
elif [ "$DB_PUSH_SWITCH" = "1" ]; then
    SSH=$STAGING_SSH
    DIR=$STAGING_DIR
    URL=$STAGING_URL
    ENVIRONMENT=staging
else
  echo "Environment not set, Toolkit Stopping"
fi

if [ "$ENVIRONMENT" ]; then
    eval wp db export db.sql;
    eval rsync -r "$LOCAL_DIR"/db.sql "$SSH":"$DIR" --stats --progress -raz --update
    ssh "$SSH" "cd $DIR; wp db import db.sql; wp search-replace '$LOCAL_URL' '$URL'; wp search-replace '$URL/wp' '$URL'; wp search-replace '$URL/app' '$URL/wp-content'; rm -rf db.sql"
    rm -rf db.sql
    echo "db updated on $ENVIRONMENT from local."
else
  echo "Environment not set, Toolkit Stopping"
fi
