#!/bin/bash
#db-pull

read -p "Database Pull
Select Environment

[0] Production
[1] Staging

[0/1]: " DB_PULL_SWITCH
if [ "$DB_PULL_SWITCH" = "0" ]; then
    SSH=$PRODUCTION_SSH
    DIR=$PRODUCTION_DIR
    URL=$PRODUCTION_URL
    ENVIRONMENT=production
elif [ "$DB_PULL_SWITCH" = "1" ]; then
    SSH=$STAGING_SSH
    DIR=$STAGING_DIR
    URL=$STAGING_URL
    ENVIRONMENT=staging
else
  echo "Environment not set, Toolkit Stopping"
fi

if [ "$ENVIRONMENT" ]; then
    ssh "$SSH" "cd $DIR; wp db export db.sql";
    eval rsync -r "$SSH":"$DIR"/db.sql "$LOCAL_DIR" --stats --progress -raz --update;
    eval "wp db import db.sql";
    wp search-replace "$URL" "$LOCAL_URL";
    wp search-replace "$LOCAL_URL/wp-content" "$LOCAL_URL/app";
    rm -rf db.sql;
    ssh "$SSH" "cd $DIR; rm -rf db.sql";
    echo "db updated on local from $ENVIRONMENT...";
else
  echo "Environment not set, Toolkit Stopping"
fi
