#!/bin/bash
#deploy

read -p "Deploy
Select Environment

[0] Production
[1] Staging

[0/1]: " ENV_SWITCH

read -p "Deploy Plugins

[0] No
[1] Yes

[0/1]: " PLUGINS_SWITCH

if [ "$ENV_SWITCH" = "0" ]; then
    SSH=$PRODUCTION_SSH
    DIR=$PRODUCTION_DIR
    ENVIRONMENT=production
elif [ "$ENV_SWITCH" = "1" ]; then
    SSH=$STAGING_SSH
    DIR=$STAGING_DIR
    ENVIRONMENT=staging
else
  echo "Environment not set, Toolkit Stopping"
fi

if [ "$ENVIRONMENT" ]; then
    echo "Deploying to $ENVIRONMENT"

    if [ "$PLUGINS_SWITCH" = "1" ]; then
        eval rsync -r "$LOCAL_DIR"/"$LOCAL_PLUGINS" "$SSH":"$DIR"/"$WP_CONTENT" --stats --progress -raz --update
    fi

    ssh "$SSH" "rm -rf $DIR/$WP_THEME/tetloose-theme;"
    ssh "$SSH" "rm -rf $DIR/$WP_THEME/tetloose-theme/acf;"
    eval rsync -r "$LOCAL_DIR"/"$LOCAL_THEME" "$SSH":"$DIR"/"$WP_THEME" --stats --progress -raz --update
    eval rsync -r "$LOCAL_DIR"/src/acf "$SSH":"$DIR"/"$WP_THEME/tetloose-theme" --stats --progress -raz --update

    echo "$ENVIRONMENT updated..."
else
    echo "Environment not set, Toolkit Stopping"
fi
