#!/bin/bash
#git-commit

# echo "$LIVE_DIR"
# echo "$STAGING_DIR"
# echo "$LOCAL_DIR"
# echo "$TEMP_DIR"
# echo "$DROPBOX_DIR"
# echo "$UPLOADS_DIR"
# echo "$LIVE_SSH"
# echo "$STAGING_SSH"
# echo "$LIVE_URL"
# echo "$STAGIN_URL"
# echo "$LOCAL_URL"
# echo "$BRANCH"

git status;
echo "Branch: $BRANCH"
read -p "Enter a commit message [ENTER]: " desc;
git add --a;
git commit -m "$desc" && \;
git push;
