#!/bin/bash
#git-commit

# echo "$PRODUCTION_SSH"
# echo "$PRODUCTION_DIR"
# echo "$PRODUCTION_URL"
# echo "$STAGING_SSH"
# echo "$STAGING_DIR"
# echo "$STAGIN_URL"
# echo "$LOCAL_DIR"
# echo "$LOCAL_URL"
# echo "$UPLOADS_DIR"
# echo "$BACKUP_DIR"
# echo "$BRANCH"

git status
echo "Branch: $BRANCH"
read -p "Enter a commit message [ENTER]: " desc
git add --a
git commit -m "$desc" && \
git push
