#!/bin/bash
#package

HASH=tetloose-$(date +"%Y-%m-%d-%h-%M-%s")

mkdir -p package/"$HASH"
mkdir -p package/"$HASH/themes"
wp search-replace "$LOCAL_URL" "$PRODUCTION_URL"
wp db export package/"$HASH"/package.sql
wp search-replace "$PRODUCTION_URL" "$LOCAL_URL"
cp -r "$LOCAL_UPLOADS" package/"$HASH"
cp -r "$LOCAL_PLUGINS" package/"$HASH"
cp -r "$LOCAL_THEME" package/"$HASH"/themes
zip -r package/"$HASH".zip package/"$HASH"
rm -rf package/"$HASH"
echo ""
echo ""
echo ""
echo Package created package/"$HASH".zip
