#!/bin/bash
#Setup

# echo "$PRODUCTION_SSH"
# echo "$PRODUCTION_DIR"
# echo "$PRODUCTION_URL"
# echo "$STAGING_SSH"
# echo "$STAGING_DIR"
# echo "$STAGIN_URL"
# echo "$LOCAL_DIR"
# echo "$LOCAL_URL"
# echo "$UPLOADS_DIR"
# echo "$BACKUP_DIR"
# echo "$BRANCH"

read -p "Setup
Choose Environment

[0] Development
[1] Production

[0/1]: " SETUP_SWITCH
if [ "$SETUP_SWITCH" = "0" ]; then
    eval "composer install; yarn; yarn postinstall; code .; yarn dev"
elif [ "$SETUP_SWITCH" = "1" ]; then
    eval "composer install; yarn; yarn build"
else
  echo "Please Enter 0 or 1, Toolkit Stopping"
fi
