#!/bin/bash

#COMMANDS
# ./toolkit setup
# ./toolkit composer
# ./toolkit backup
# ./toolkit merge-branch
# ./toolkit git-commit
# ./toolkit uploads-push
# ./toolkit uploads-pull
# ./toolkit db-push
# ./toolkit db-pull
# ./toolkit deploy

ENV=.env
if test -f "$ENV"; then
  LIVE_DIR=$(grep TOOLKIT_LIVE_DIR $ENV | cut -d '=' -f2)
  STAGING_DIR=$(grep TOOLKIT_STAGING_DIR $ENV | cut -d '=' -f2)
  LOCAL_DIR=$(grep TOOLKIT_LOCAL_DIR $ENV | cut -d '=' -f2)
  TEMP_DIR=$(grep TOOLKIT_TEMP_DIR $ENV | cut -d '=' -f2)
  DROPBOX_DIR=$(grep TOOLKIT_DROPBOX_DIR $ENV | cut -d '=' -f2)
  UPLOADS_DIR=$(grep TOOLKIT_UPLOADS_DIR $ENV | cut -d '=' -f2)
  LIVE_SSH=$(grep TOOLKIT_LIVE_SSH $ENV | cut -d '=' -f2)
  STAGING_SSH=$(grep TOOLKIT_STAGING_SSH $ENV | cut -d '=' -f2)
  LIVE_URL=$(grep TOOLKIT_LIVE_URL $ENV | cut -d '=' -f2)
  STAGIN_URL=$(grep TOOLKIT_STAGIN_URL $ENV | cut -d '=' -f2)
  LOCAL_URL=$(grep TOOLKIT_LOCAL_URL $ENV | cut -d '=' -f2)

  export LIVE_DIR
  export STAGING_DIR
  export LOCAL_DIR
  export TEMP_DIR
  export DROPBOX_DIR
  export UPLOADS_DIR
  export LIVE_SSH
  export STAGING_SSH
  export LIVE_URL
  export STAGIN_URL
  export LOCAL_URL

  clear
  echo "Starting Tetloose WP TOOLKIT..."
  echo "toolkit $1"
else
  echo "Local $ENV doesn't exist, generating now"
  eval "wp dotenv init --template=$ENV.example --interactive --with-salts --force"
  eval "sh ./toolkit $1"
fi

# else
# # git config --global core.pager cat
# # branch=$(git branch | sed -n -e 's/^\* \(.*\)/\1/p')

# ./toolkit setup
if [ "$1" = "setup" ]; then
  eval "sh .scripts/$1"

else
  echo "Stop saying that Withnail, of course he's the fucking farmer!"
fi
