#!/bin/bash
#uploads-push

read -p "Uploads Push
Select Environment

[0] Production
[1] Staging

[0/1]: " UPLOADS_PUSH_SWITCH
if [ "$UPLOADS_PUSH_SWITCH" = "0" ]; then
    SSH=$PRODUCTION_SSH
    DIR=$PRODUCTION_DIR
    ENVIRONMENT=production
elif [ "$UPLOADS_PUSH_SWITCH" = "1" ]; then
    SSH=$STAGING_SSH
    DIR=$STAGING_DIR
    ENVIRONMENT=staging
else
  echo "Environment not set, Toolkit Stopping"
fi

if [ "$ENVIRONMENT" ]; then
    eval "cd $LOCAL_DIR/$LOCAL_APP; zip -r -D uploads.zip uploads"
    eval rsync "$LOCAL_DIR"/$LOCAL_APP/uploads.zip "$SSH":"$DIR"/$WP_CONTENT --stats --progress -zvrt --update
    ssh "$SSH" "cd $DIR/$WP_CONTENT; unzip -o uploads.zip"
    eval "rm -rf $LOCAL_DIR/$LOCAL_APP/uploads.zip"
    ssh "$SSH" "rm -rf $DIR/$WP_CONTENT/uploads.zip"
    echo "Uploads pushed from Local to $ENVIRONMENT."
else
  echo "Environment not set, Toolkit Stopping"
fi
