#!/bin/bash
#uploads-pull

read -p "Uploads Pull
Select Environment

[0] Production
[1] Staging

[0/1]: " UPLOADS_PULL_SWITCH
if [ "$UPLOADS_PULL_SWITCH" = "0" ]; then
    SSH=$PRODUCTION_SSH
    DIR=$PRODUCTION_DIR
    ENVIRONMENT=production
elif [ "$UPLOADS_PULL_SWITCH" = "1" ]; then
    SSH=$STAGING_SSH
    DIR=$STAGING_DIR
    ENVIRONMENT=staging
else
  echo "Environment not set, Toolkit Stopping"
fi

if [ "$ENVIRONMENT" ]; then
    ssh "$SSH" "cd $DIR/$WP_CONTENT; zip -r -D uploads.zip uploads"
    eval rsync "$SSH":"$DIR"/$WP_CONTENT/uploads.zip "$LOCAL_DIR"/$LOCAL_APP --stats --progress -zvrt --update
    ssh "$SSH" "rm -rf $DIR/$WP_CONTENT/uploads.zip"
    eval "cd $LOCAL_DIR/$LOCAL_APP" unzip -o uploads.zip
    eval rm -rf "$LOCAL_DIR"/$LOCAL_APP/uploads.zip
    echo "Uploads pulled from $ENVIRONMENT to local."
else
  echo "Environment not set, Toolkit Stopping"
fi
