#!/bin/bash
#uploads-pull

# echo "$PRODUCTION_SSH"
# echo "$PRODUCTION_DIR"
# echo "$PRODUCTION_URL"
# echo "$STAGING_SSH"
# echo "$STAGING_DIR"
# echo "$STAGIN_URL"
# echo "$LOCAL_DIR"
# echo "$LOCAL_URL"
# echo "$UPLOADS_DIR"
# echo "$BACKUP_DIR"
# echo "$BRANCH"

read -p "Uploads Pull
Select Environment

[0] Staging
[1] Production

[0/1]: " UPLOADS_PULL_SWITCH
if [ "$UPLOADS_PULL_SWITCH" = "0" ]; then
    SSH=$PRODUCTION_SSH
    DIR=$PRODUCTION_DIR
    ENVIRONMENT=staging
elif [ "$UPLOADS_PULL_SWITCH" = "1" ]; then
    SSH=$STAGING_SSH
    DIR=$STAGING_DIR
    ENVIRONMENT=production
else
  echo "Please Enter 0 or 1, Toolkit Stopping"
fi

if [ "$ENVIRONMENT" ]; then
    ssh "$SSH" "cd $DIR/web/app; zip -r -D uploads.zip uploads"
    eval rsync "$SSH":"$DIR"/web/app/uploads.zip "$LOCAL_DIR"/web/app --stats --progress -zvrt --update
    ssh "$SSH" "rm -rf $DIR/web/app/uploads.zip"
    eval "cd $LOCAL_DIR/web/app" unzip -o uploads.zip
    eval rm -rf "$LOCAL_DIR"/web/app/uploads.zip
    echo "Uploads pulled from $ENVIRONMENT to local."
fi
