// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'click': string;
  'scc': string;
}
export const cssExports: CssExports;
export default cssExports;
