// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bg-dark': string;
  'header': string;
  'header__cta': string;
  'header__cta-link': string;
  'header__logo': string;
}
export const cssExports: CssExports;
export default cssExports;
